### ISSUE TITLE
Weird redirect.

### ISSUE THREAD

**Issue by HaoZeke** [itsmegb/LazyLibrarian#83]
Hi,
With my webroot setup along with nginx, I'm getting a strange hard redirect to http://127.0.0.1:5299/lazylib/

Relevant configs:

Nginx

```
# Outside server block
upstream lazylib {
    server lazylib:5299;
}


# In the server block
  # Lazy Librarian
  location /lazylib {
    proxy_pass http://lazylib;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_redirect default;
  }
```

Docker compose details:

```
# LazyLibrarian [Book Stuff]
  lazylib:
    image: linuxserver/lazylibrarian:latest
    container_name: "LazyLibrarian"
    networks:
      - webgateway
    expose:
      - 5299
    volumes:
      - ${LAZYLIB_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
      - ${CALIBRE_LIBRARY_PATH}:/books
    depends_on:
      - transmission
```

It's odd because the exact same setup works correctly for headphones, sonarr, radarr etc...
